"""Add indexes for search optimization

Revision ID: 3ef1ed66aae4
Revises: 6cdbf1591d0c
Create Date: 2025-11-09 17:58:44.930168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef1ed66aae4'
down_revision: Union[str, None] = '6cdbf1591d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_vectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_track_vectors_track_id'))

    op.drop_table('track_vectors')
    op.drop_table('track_vectors_virtual')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_index('idx_album_title', ['title'], unique=False)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.create_index('idx_artist_name', ['name'], unique=False)

    with op.batch_alter_table('genre_tags', schema=None) as batch_op:
        batch_op.create_index('idx_genre_tag_name', ['name'], unique=False)

    with op.batch_alter_table('mood_tags', schema=None) as batch_op:
        batch_op.create_index('idx_mood_tag_name', ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_mood_tag_name')

    with op.batch_alter_table('genre_tags', schema=None) as batch_op:
        batch_op.drop_index('idx_genre_tag_name')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_index('idx_artist_name')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_index('idx_album_title')

    op.create_table('track_vectors_virtual',
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('embedding', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('track_id', name=op.f('pk_track_vectors_virtual'))
    )
    op.create_table('track_vectors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=False),
    sa.Column('vector_data', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_vectors_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_track_vectors'))
    )
    with op.batch_alter_table('track_vectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_track_vectors_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###
