"""fix link for covers

Revision ID: 0e2761ec7135
Revises: 2d26be6a3a82
Create Date: 2025-05-31 19:24:54.627885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2761ec7135'
down_revision: Union[str, None] = '2d26be6a3a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_entity_cover', ['entity_type', 'entity_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_entity_cover', type_='unique')

    # ### end Alembic commands ###
