"""Add artist relationship to ArtistSimilar model

Revision ID: 1e1b8a545019
Revises: merge_fix_artists_trigger
Create Date: 2025-12-06 19:08:33.360376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e1b8a545019'
down_revision: Union[str, None] = 'merge_fix_artists_trigger'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(), nullable=False),
    sa.Column('vector', sa.Text(), nullable=False),
    sa.Column('cluster', sa.Integer(), nullable=True),
    sa.Column('cluster_probabilities', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artist_embeddings'))
    )
    with op.batch_alter_table('artist_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_embeddings_artist_name'), ['artist_name'], unique=True)

    op.create_table('gmm_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('n_components', sa.Integer(), nullable=False),
    sa.Column('convergence_threshold', sa.Float(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('n_features', sa.Integer(), nullable=False),
    sa.Column('log_likelihood', sa.Float(), nullable=True),
    sa.Column('model_weights', sa.Text(), nullable=False),
    sa.Column('model_means', sa.Text(), nullable=False),
    sa.Column('model_covariances', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gmm_models'))
    )
    with op.batch_alter_table('gmm_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmm_models_is_active'), ['is_active'], unique=False)

    op.drop_table('artist_genre_links')
    with op.batch_alter_table('ArtistSimilar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_similar_artist_id'))
        batch_op.drop_index(batch_op.f('ix_artist_similar_similar_artist_id'))
        batch_op.drop_index(batch_op.f('ix_artist_similar_weight'))

    op.drop_table('ArtistSimilar')
    op.drop_table('album_genre_links')
    op.drop_table('track_genre_links')
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('date_modified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('fk_albums_album_artist_id_artists'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_albums_album_artist_id_artists'), 'artists', ['album_artist_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('lastfm_similar_artists_fetched',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('date_modified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('ix_artists_lastfm_similar_fetched'))
        batch_op.create_unique_constraint(batch_op.f('uq_artists_name'), ['name'])

    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.alter_column('entity_type',
               existing_type=postgresql.ENUM('TRACK', 'ALBUM', 'ARTIST', name='covertype'),
               type_=sa.Enum('TRACK', 'ALBUM', 'ARTIST', name='covertype'),
               existing_nullable=False)
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('date_modified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('scan_sessions', schema=None) as batch_op:
        batch_op.alter_column('processed_files',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('is_encrypted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('date_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index('idx_tracks_artist_album', ['track_artist_id', 'album_id'], unique=False)
        batch_op.create_index('idx_tracks_dates', ['date_added', 'date_modified'], unique=False)
        batch_op.create_index('idx_tracks_genre', ['genre'], unique=False)
        batch_op.create_index('idx_tracks_mb_id', ['musicbrainz_id'], unique=False)
        batch_op.create_index('idx_tracks_missing_audio', ['bpm', 'key'], unique=False)
        batch_op.create_index('idx_tracks_path', ['path'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_tracks_track_artist_id_artists'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tracks_track_artist_id_artists'), 'artists', ['track_artist_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tracks_track_artist_id_artists'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tracks_track_artist_id_artists'), 'artists', ['track_artist_id'], ['id'])
        batch_op.drop_index('idx_tracks_path')
        batch_op.drop_index('idx_tracks_missing_audio')
        batch_op.drop_index('idx_tracks_mb_id')
        batch_op.drop_index('idx_tracks_genre')
        batch_op.drop_index('idx_tracks_dates')
        batch_op.drop_index('idx_tracks_artist_album')
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.alter_column('date_modified',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('is_encrypted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('scan_sessions', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('processed_files',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.alter_column('date_modified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('entity_type',
               existing_type=sa.Enum('TRACK', 'ALBUM', 'ARTIST', name='entitycovertype'),
               type_=postgresql.ENUM('TRACK', 'ALBUM', 'ARTIST', name='entitycovertype'),
               existing_nullable=False)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_artists_name'), type_='unique')
        batch_op.create_index(batch_op.f('ix_artists_lastfm_similar_fetched'), ['lastfm_similar_artists_fetched'], unique=False)
        batch_op.alter_column('date_modified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('lastfm_similar_artists_fetched',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_albums_album_artist_id_artists'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_albums_album_artist_id_artists'), 'artists', ['album_artist_id'], ['id'])
        batch_op.alter_column('date_modified',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.create_table('track_genre_links',
    sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_track_genre_links_genre_id_genres')),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_genre_links_track_id_tracks'))
    )
    op.create_table('album_genre_links',
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_album_genre_links_album_id_albums')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_album_genre_links_genre_id_genres'))
    )
    op.create_table('ArtistSimilar',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('similar_artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_ArtistSimilar_artist_id_artists')),
    sa.ForeignKeyConstraint(['similar_artist_id'], ['artists.id'], name=op.f('fk_ArtistSimilar_similar_artist_id_artists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ArtistSimilar')),
    sa.UniqueConstraint('artist_id', 'similar_artist_id', name=op.f('unique_artist_similar'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('ArtistSimilar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_similar_weight'), ['weight'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_similar_similar_artist_id'), ['similar_artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artist_similar_artist_id'), ['artist_id'], unique=False)

    op.create_table('artist_genre_links',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_artist_genre_links_artist_id_artists')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_artist_genre_links_genre_id_genres'))
    )
    with op.batch_alter_table('gmm_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmm_models_is_active'))

    op.drop_table('gmm_models')
    with op.batch_alter_table('artist_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_embeddings_artist_name'))

    op.drop_table('artist_embeddings')
    # ### end Alembic commands ###
