"""simplify_cover_relations

Revision ID: 456a421e083a
Revises: 0e2761ec7135
Create Date: 2025-05-31 19:29:50.879256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456a421e083a'
down_revision: Union[str, None] = '0e2761ec7135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.create_index('idx_entity_lookup', ['entity_type', 'entity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.drop_index('idx_entity_lookup')

    # ### end Alembic commands ###
