"""Correct covers model

Revision ID: 946ee9dfb744
Revises: 1efbe5e77d3a
Create Date: 2025-05-30 17:49:36.901272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946ee9dfb744'
down_revision: Union[str, None] = '1efbe5e77d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_entity_cover', ['entity_type', 'entity_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.drop_constraint('uix_entity_cover', type_='unique')

    # ### end Alembic commands ###
