"""add_date_modified_to_track_mir_synthetic_tags

Revision ID: 9dcc1e232cef
Revises: zzzzzz_merge_all_heads_final
Create Date: 2026-03-05 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9dcc1e232cef'
down_revision: Union[str, None] = 'zzzzzz_merge_all_heads_final'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_mir_synthetic_tags', sa.Column('date_modified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('track_mir_synthetic_tags', sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_mir_synthetic_tags', 'date_modified')
    op.drop_column('track_mir_synthetic_tags', 'date_added')
    # ### end Alembic commands ###
