"""harmonize models and add missing fields

Revision ID: a90d361a9e8e
Revises: 6de1ee8409d1
Create Date: 2025-05-10 19:11:36.771878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90d361a9e8e'
down_revision: Union[str, None] = '6de1ee8409d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.create_unique_constraint("musicbrain_id", ['musicbrainz_albumid'])
        batch_op.drop_column('genre')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_modified', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musicbrainz_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint("musicbrain_id", ['musicbrainz_id'])
        batch_op.drop_column('release_date')
        batch_op.drop_column('musicbrain_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('musicbrain_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('musicbrainz_id')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('date_modified')
        batch_op.drop_column('date_added')
        batch_op.drop_column('cover_url')

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
