"""Correct covers model 3

Revision ID: aff6b78e03f0
Revises: 8c902ff3911d
Create Date: 2025-05-30 17:59:07.968082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff6b78e03f0'
down_revision: Union[str, None] = '8c902ff3911d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.drop_constraint('uix_entity_cover', type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('covers', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_entity_cover', ['entity_type', 'entity_id'])

    # ### end Alembic commands ###
