"""2nd  mligration

Revision ID: baccf0659204
Revises: 40139eb7261b
Create Date: 2025-05-31 18:48:06.763532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baccf0659204'
down_revision: Union[str, None] = '40139eb7261b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('instrumental',
               existing_type=sa.BOOLEAN(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('acoustic',
               existing_type=sa.BOOLEAN(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('tonal',
               existing_type=sa.BOOLEAN(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('tonal',
               existing_type=sa.Float(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('acoustic',
               existing_type=sa.Float(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('instrumental',
               existing_type=sa.Float(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
