"""Add covers model bis

Revision ID: f39730921623
Revises: 3c54acbe949f
Create Date: 2025-05-24 18:53:34.956475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39730921623'
down_revision: Union[str, None] = '3c54acbe949f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('album_artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('date_added',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint('uq_albums_musicbrainz_albumid', type_='unique')
        batch_op.drop_column('musicbrainz_albumartistid')
        batch_op.drop_column('genre')
        batch_op.drop_column('cover_url')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('uq_artists_musicbrainz_artistid', type_='unique')
        batch_op.drop_column('genre')
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), nullable=True))
        batch_op.create_unique_constraint('uq_artists_musicbrainz_artistid', ['musicbrainz_artistid'])
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('musicbrainz_albumartistid', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_albums_musicbrainz_albumid', ['musicbrainz_albumid'])
        batch_op.alter_column('date_modified',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('date_added',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('album_artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
