"""Complete  tags models

Revision ID: f8da41b6ee5d
Revises: f0e817915b8e
Create Date: 2025-05-24 14:47:05.522904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8da41b6ee5d'
down_revision: Union[str, None] = 'f0e817915b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_genre_tags_id')
        batch_op.drop_index('ix_genre_tags_name')
        batch_op.create_unique_constraint(batch_op.f('uq_genre_tags_name'), ['name'])

    with op.batch_alter_table('mood_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_mood_tags_id')
        batch_op.drop_index('ix_mood_tags_name')
        batch_op.create_unique_constraint(batch_op.f('uq_mood_tags_name'), ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_mood_tags_name'), type_='unique')
        batch_op.create_index('ix_mood_tags_name', ['name'], unique=1)
        batch_op.create_index('ix_mood_tags_id', ['id'], unique=False)

    with op.batch_alter_table('genre_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_genre_tags_name'), type_='unique')
        batch_op.create_index('ix_genre_tags_name', ['name'], unique=1)
        batch_op.create_index('ix_genre_tags_id', ['id'], unique=False)

    # ### end Alembic commands ###
