from __future__ import annotations
from typing import Annotated
from strawberry import auto
from backend.api.graphql.strawchemy_init import strawchemy

from backend.api.models.albums_model import Album
@strawchemy.order(Album, include="all")
class AlbumOrderedType: ...
@strawchemy.filter(Album, include="all")
class AlbumFilterType: ...
@strawchemy.type(Album, include="all",filter_input=AlbumFilterType, order_by=AlbumOrderedType, override=True)
class AlbumType: ...

@strawchemy.create_input(Album, include="all")
class AlbumCreateInputType: ...
@strawchemy.pk_update_input(Album, include="all")
class AlbumUpdateInputType: ...

@strawchemy.filter_update_input(Album, include="all")
class AlbumFilterUpdateInputType: ...
@strawchemy.upsert_conflict_fields(Album, include=["id", "musicbrainz_id", "title", "album_artist_id "])
class AlbumUpsertConflictFieldsType: ...

@strawchemy.upsert_update_fields(Album, include=["title", "release_date", "musicbrainz_id", "album_artist_id"])
class AlbumUpsertUpdateFieldsType: ...
